#Application
spring:
  application:
    name: @artifactId@
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/ingjulianvega/mssc-asu-config-repo
          search-paths: '{application}'
server:
  port: 8113
#Logging
logging:
  level:
    org.springframework.cloud: DEBUG
    org.springframework.web: DEBUG
